#!/bin/bash
# This script should create a Factorio mod that uses the Musitorio library to
# add music (.ogg, .mp3, .flac, and .wav) and a thumbnail (.png or .jpg) from a
# folder given as an argument
#set -e
shopt -s extglob

numtracks=0

inputfolder=$(echo "$1" | sed -e "s/\/$//")
projectname=$(echo "$2" | sed -e "s/\/$//;s/.*/\L&/")
niceprojectname=$(echo "$projectname" | sed -e "s/[a-z']*/\u&/g")
outputfolder=musitorio-"$projectname"

importantfile="$outputfolder"/prototypes/"$projectname".lua


for file in "$inputfolder"/*.?(jpg|png); do
  thumbnail="$file"
done

mkdir -p "$outputfolder"

ffmpeg -i "$thumbnail" "$outputfolder"/thumbnail.png

# create the most important file
mkdir -p "$outputfolder"/prototypes
echo "local musitorio = require(\"__libmusitorio__.functions.musitorio\")
add_music({" > "$importantfile"


mkdir -p "$outputfolder"/audio
for file in "$inputfolder"/*.?(ogg|flac|mp3|wav); do
  if [[ "$file" == *.?(ogg|wav) ]]; then # if the file is an ogg or wav just copy it
    output=$(echo "$file" | sed -e "s/^.*\///;s/.*/\L&/;s/[ _]/-/g;s/^[123456789][^0123456789]/0&/") # this regex removes everything up to the last "/", makes everything lowercase, replaces " " and "_" with "-", and replaces a digit at the start the line followed by a non-digit with 0 and the matched text
    cp "$file" "$outputfolder"/audio/"$output"
  else # otherwise transcode it
    output=$(echo "$file" | sed -e "s/^.*\///;s/.*/\L&/;s/flac$\|mp3$/ogg/;s/[ _]/-/g;s/^[123456789][^0123456789]/0&/")
    ffmpeg -i "$file" "$outputfolder"/audio/"$output"
  fi
  
  trackname=$(echo "$file" | sed -e "s/^.*\///;s/.*/\L&/;s/.flac$\|.mp3$\|.ogg$\|.wav$//")
  if [[ $numtracks > 0 ]]; then
    echo -n ",
    {trackname = \"$trackname\", file = \"__${outputfolder}__/audio/"$output"\"}" >> "$importantfile"
  else
    echo -n "    {trackname = \"$trackname\", file = \"__${outputfolder}__/audio/"$output"\"}" >> "$importantfile"
  fi
  
  let "numtracks++"
done
echo "
}, settings.startup[\"$projectname-menu-track\"].value, settings.startup[\"$projectname-include-menu-track\"].value)" >> "$importantfile"

# Now we create the other important files
echo "local musitorio = require(\"__libmusitorio__.functions.musitorio\")

musitorio_settings(\"$projectname\", $numtracks)" > "$outputfolder"/settings.lua

echo "{
    \"name\": \"$outputfolder\",
    \"version\": \"0.0.1\",
    \"factorio_version\": \"1.1\",
    \"title\": \"$niceprojectname Music Pack\",
    \"author\": \"YOUR NAME HERE\",
    \"contact\": \"blank\",
    \"description\": \"Autogenerated by Musitorio's autogen.sh\",
    \"dependencies\":
    [
        \"base\",
        \"libmusitorio\"
    ]
}" > "$outputfolder"/info.json

echo "require(\"prototypes.$projectname\")" > "$outputfolder"/data.lua

echo "TODO for user: find a license that will work with the music" > "$outputfolder"/LICENSE

mkdir -p "$outputfolder"/locale/en
echo "[mod-setting-name]
$projectname-menu-track=Track number for the menu track
$projectname-include-menu-track=Include menu track with main tracks

[mod-setting-description]
$projectname-menu-track=0 is a special number that means no menu music will be set
$projectname-include-menu-track=If true, a second prototype will be created meaning the menu track will appear while in-game" > "$outputfolder"/locale/en/settings.cfg
